feat: improve garm-provider dev setup and adjust docs for new garm v0.1.5
mercedes-benz/garm-provider-k8s pull request #78
Opened 2024-12-03 11:33 UTC by rafalgalaw

fixes #71 
see title

2025-04-02 12:14 UTC, rafalgalaw commented on hack/local-development/kubernetes/garm-operator-crs-envsubst.yaml
> +# nonk8s
fixed with #d5dfdaa

2025-04-02 12:15 UTC, rafalgalaw commented on DEVELOPMENT.md
> +     * `Webhooks: Read & write` - needed to install webhooks on repositories
fixed with d5dfdaa

2025-04-02 12:15 UTC, rafalgalaw commented on DEVELOPMENT.md
> +     * `Webhooks: Read & write` - needed to install webhooks on organizations
fixed with d5dfdaa

2025-04-02 12:16 UTC, rafalgalaw commented on .gitignore
> -/hack/local-development/kubernetes/garm-operator-all.yaml
fixed with d5dfdaa

2025-04-10 13:02 UTC, bavarianbidi requested changes

2025-04-10 13:02 UTC, bavarianbidi commented on Makefile
> +	@mkdir -p ./hack/bine
```suggestion
	@mkdir -p ./hack/bin
```

this seems to be a typo :-)

2025-04-15 04:18 UTC, bavarianbidi approved these changes

2025-04-15 04:20 UTC, bavarianbidi commented
please add the license-header to the `.gitleaksignore` file (same as we do on `.gitignore` - https://github.com/mercedes-benz/garm-provider-k8s/blob/main/.gitignore#L1 )
```
./hack/scripts/verify-license.sh
error checking .gitleaksignore for the SPDX header

Please review the above files. They seem to miss the following header as comment:
SPDX-License-Identifier: MIT

make: *** [Makefile:176: verify-license] Error 1
```

2025-04-15 11:58 UTC, merged